apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pydjan-app-db-password
  namespace: storefront-devpydja
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: teams-dev/storefront-devpydja/DB_PASSWORD
