apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pydjan-app-cdn-api-secret
  namespace: storefront-devpydja
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: CDN_API_SECRET
      remoteRef:
        key: teams-dev/storefront-devpydja/CDN_API_SECRET
