# syntax=docker/dockerfile:1
# Generated by DeepAgent. Rerunning the deploy regenerates this file — delete this line to keep your own edits.
# --- Asset stage: build the JavaScript this app serves itself ---
FROM node:20-bookworm-slim AS assets
WORKDIR /src
COPY frontend/package.json frontend/pnpm-lock.yaml* frontend/pnpm-workspace.yaml* frontend/.npmrc* frontend/
RUN cd frontend && npm pkg delete scripts.prepare scripts.postinstall >/dev/null 2>&1 || true && corepack enable && export PNPM_CONFIG_DANGEROUSLY_ALLOW_ALL_BUILDS=true && (if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; else pnpm install; fi)
COPY . .
# The repo's own postinstall, now that the files it reads are here.
RUN cd frontend && npm run postinstall --if-present
RUN cd frontend && pnpm run build
# Build-only dependencies never reach the runtime image.
RUN rm -rf frontend/node_modules

FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1
WORKDIR /app
# Copy the whole build context first, then detect which Python packaging
# shape the repo uses. Was hardcoded to `COPY requirements.txt` and blew up
# for every repo using pyproject.toml / Pipfile / poetry.lock — the Dockerfile
# demanded a file that didn't exist and the build died on step 3/7 with
# "'requirements.txt': not found" (2026-09-09, deepagent-generated backend
# scaffold). Detecting at build time handles every shape without asking.
# uv is checked FIRST: its lockfile is the most specific statement of what
# to install, and `uv export` turns it into pinned requirements for the
# system pip (no venv to point PATH at). A pyproject with no [build-system]
# is a uv/PEP 621 "virtual" project — `pip install .` has nothing to build,
# so its dependencies are installed from the [project] table instead.
COPY . .
RUN set -eu; \
    python -m pip install --no-cache-dir --upgrade pip; \
    if [ -f uv.lock ]; then \
      pip install --no-cache-dir uv && \
      uv export --frozen --no-dev --no-hashes --no-emit-project -o /tmp/requirements.txt && \
      pip install --no-cache-dir -r /tmp/requirements.txt; \
    elif [ -f pyproject.toml ] && [ -f poetry.lock ]; then \
      pip install --no-cache-dir poetry && \
      poetry config virtualenvs.create false --local && \
      poetry install --only main --no-interaction --no-ansi --no-root; \
    elif [ -f Pipfile.lock ]; then \
      pip install --no-cache-dir pipenv && \
      pipenv install --deploy --system; \
    elif [ -f requirements.txt ]; then \
      pip install --no-cache-dir -r requirements.txt; \
    elif [ -f pyproject.toml ]; then \
      if grep -q '^\[build-system\]' pyproject.toml; then \
        pip install --no-cache-dir .; \
      else \
        pip install --no-cache-dir uv && uv pip install --system --no-cache -r pyproject.toml; \
      fi; \
    else \
      echo "ERROR: no Python packaging file found (uv.lock, poetry.lock, Pipfile.lock, requirements.txt or pyproject.toml)" >&2; \
      exit 1; \
    fi
# The built assets, replacing the un-built frontend/ copied above.
COPY --from=assets /src/frontend ./frontend
# Django serves the bundle through its static pipeline, so the files
# have to be collected at BUILD time: the runtime filesystem is
# read-only under the platform's security profile.
RUN python manage.py collectstatic --noinput

# Non-root runtime user. USER must be a NUMERIC uid — Kubernetes'
# runAsNonRoot check refuses to start a container whose USER is a name,
# because it cannot verify from outside the image that the name is non-root
# (2026-09, java-app-backend hit CreateContainerConfigError under the
# restricted profile because USER was "app" instead of a number).
RUN useradd --create-home --uid 10001 appuser && chown -R appuser /app
USER 10001
EXPOSE 8000
CMD ["python3","manage.py","runserver"]
