apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pydjan-app-cdn-api-key
  namespace: storefront-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: CDN_API_KEY
      remoteRef:
        key: storefront-dev/storefront-dev/CDN_API_KEY
