apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pydjan-frontend-auth-token
  namespace: storefront-devpydja
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: AUTH_TOKEN
      remoteRef:
        key: teams-dev/storefront-devpydja/AUTH_TOKEN
